services:
  app:
    build: .
    ports:
      - '8081:80'
    volumes:
      - ./app:/var/www/html/
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8082:80'